In [4]:
import numpy as np
np.__version__

'2.2.2'

Python listesinden Numpy arrayi oluşturma

In [6]:
np.array([1,4,2,5,3])

array([1, 4, 2, 5, 3])

NpArrayin tipini baştan belirleyebiliriz

In [7]:
np.array([1,4,2,5,3], dtype='float32')

array([1., 4., 2., 5., 3.], dtype=float32)

Numpy ile multidimensional array tanımlama

In [8]:
np.array([range(i,i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

NOTE: Nested listeler otomatik olarak multidimensional olur

In [9]:
np.full((3,5),3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [11]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [22]:
x[: ,np.newaxis]

array([[1],
       [2],
       [3]])

In [29]:
np.random.seed(0)

def compute_reciprocals(values):
 output = np.empty(len(values))
 for i in range(len(values)):
     output[i] = 1.0 / values[i]
 return output

    
 values = np.random.randint(1, 10, size=5)
 compute_reciprocals(values)

In [31]:
big_array = np.random.randint(1, 100, size=1000000)
%timeit compute_reciprocals(big_array)

4.68 s ± 176 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [39]:
print(type(big_array.min()))

<class 'numpy.int32'>


In [54]:
help(np.zeros_like)

Help on _ArrayFunctionDispatcher in module numpy:

zeros_like(a, dtype=None, order='K', subok=True, shape=None, *, device=None)
    Return an array of zeros with the same shape and type as a given array.

    Parameters
    ----------
    a : array_like
        The shape and data-type of `a` define these same attributes of
        the returned array.
    dtype : data-type, optional
        Overrides the data type of the result.
    order : {'C', 'F', 'A', or 'K'}, optional
        Overrides the memory layout of the result. 'C' means C-order,
        'F' means F-order, 'A' means 'F' if `a` is Fortran contiguous,
        'C' otherwise. 'K' means match the layout of `a` as closely
        as possible.
    subok : bool, optional.
        If True, then the newly created array will use the sub-class
        type of `a`, otherwise it will be a base-class array. Defaults
        to True.
    shape : int or sequence of ints, optional.
        Overrides the shape of the result. If order='K' and 

In [55]:
help( np.searchsorted)

Help on _ArrayFunctionDispatcher in module numpy:

searchsorted(a, v, side='left', sorter=None)
    Find indices where elements should be inserted to maintain order.

    Find the indices into a sorted array `a` such that, if the
    corresponding elements in `v` were inserted before the indices, the
    order of `a` would be preserved.

    Assuming that `a` is sorted:

    ======  ============================
    `side`  returned index `i` satisfies
    ======  ============================
    left    ``a[i-1] < v <= a[i]``
    right   ``a[i-1] <= v < a[i]``
    ======  ============================

    Parameters
    ----------
    a : 1-D array_like
        Input array. If `sorter` is None, then it must be sorted in
        ascending order, otherwise `sorter` must be an array of indices
        that sort it.
    v : array_like
        Values to insert into `a`.
    side : {'left', 'right'}, optional
        If 'left', the index of the first suitable location found is given.
       

In [9]:
data = np.zeros(4, dtype={'names':('name', 'age', 'weight'),'formats':('U10', 'i4', 'f8')})
print(data.dtype)
print(data)

[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')]
[('', 0, 0.) ('', 0, 0.) ('', 0, 0.) ('', 0, 0.)]
